const CONTEUDO = {
  brand: 'F · L',
  eyebrow: 'Uma identidade • Uma história',
  heroTexto: 'FERREIRA LARANJEIRA — uma marca construída sobre tradição, propósito e futuro.',
  botaoHero: 'Conheça a história',
  historiaEyebrow: 'Nossa essência',
  historiaTitulo: 'Uma assinatura que atravessa gerações',
  historiaTexto: 'Ferreira Laranjeira representa a união entre raízes e visão. O monograma FL traduz força e elegância, enquanto o ramo de laranjeira simboliza origem, crescimento e continuidade.',
  valoresEyebrow: 'O que nos representa',
  valoresTitulo: 'Tradição. Propósito. Futuro.',
  tradicaoTitulo: 'Tradição',
  tradicaoTexto: 'Respeito às origens e aos valores que formam nossa identidade.',
  propositoTitulo: 'Propósito',
  propositoTexto: 'Uma identidade feita para representar quem somos e aquilo que construímos.',
  futuroTitulo: 'Futuro',
  futuroTexto: 'Olhar adiante sem perder a essência que nos trouxe até aqui.',
  frase: '“Raízes profundas permitem que grandes histórias continuem crescendo.”',
  fraseAutor: 'Ferreira Laranjeira',
  contatoEyebrow: 'Ferreira Laranjeira',
  contatoTitulo: 'Faça parte da história',
  contatoTexto: 'Uma identidade para família, projetos, negócios e tudo aquilo que merece deixar uma marca.',
  email: 'contato@ferreiralaranjeira.com',
  botaoContato: 'Entrar em contato',
  rodape: '© 2026 FERREIRA LARANJEIRA • TRADIÇÃO · PROPÓSITO · FUTURO'
};
